# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Pudge/Chat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Pudge/Chat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Pudge/Chat/CMakeFiles /home/Pudge/Chat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Pudge/Chat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chat.out

# Build rule for target.
chat.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chat.out
.PHONY : chat.out

# fast build rule for target.
chat.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/build
.PHONY : chat.out/fast

AuthData.o: AuthData.cpp.o
.PHONY : AuthData.o

# target to build an object file
AuthData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/AuthData.cpp.o
.PHONY : AuthData.cpp.o

AuthData.i: AuthData.cpp.i
.PHONY : AuthData.i

# target to preprocess a source file
AuthData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/AuthData.cpp.i
.PHONY : AuthData.cpp.i

AuthData.s: AuthData.cpp.s
.PHONY : AuthData.s

# target to generate assembly for a file
AuthData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/AuthData.cpp.s
.PHONY : AuthData.cpp.s

Chat.o: Chat.cpp.o
.PHONY : Chat.o

# target to build an object file
Chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Chat.cpp.o
.PHONY : Chat.cpp.o

Chat.i: Chat.cpp.i
.PHONY : Chat.i

# target to preprocess a source file
Chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Chat.cpp.i
.PHONY : Chat.cpp.i

Chat.s: Chat.cpp.s
.PHONY : Chat.s

# target to generate assembly for a file
Chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Chat.cpp.s
.PHONY : Chat.cpp.s

Client.o: Client.cpp.o
.PHONY : Client.o

# target to build an object file
Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Client.cpp.o
.PHONY : Client.cpp.o

Client.i: Client.cpp.i
.PHONY : Client.i

# target to preprocess a source file
Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Client.cpp.i
.PHONY : Client.cpp.i

Client.s: Client.cpp.s
.PHONY : Client.s

# target to generate assembly for a file
Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Client.cpp.s
.PHONY : Client.cpp.s

Connection.o: Connection.cpp.o
.PHONY : Connection.o

# target to build an object file
Connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Connection.cpp.o
.PHONY : Connection.cpp.o

Connection.i: Connection.cpp.i
.PHONY : Connection.i

# target to preprocess a source file
Connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Connection.cpp.i
.PHONY : Connection.cpp.i

Connection.s: Connection.cpp.s
.PHONY : Connection.s

# target to generate assembly for a file
Connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Connection.cpp.s
.PHONY : Connection.cpp.s

Logger.o: Logger.cpp.o
.PHONY : Logger.o

# target to build an object file
Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Logger.cpp.o
.PHONY : Logger.cpp.o

Logger.i: Logger.cpp.i
.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s
.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

Message.o: Message.cpp.o
.PHONY : Message.o

# target to build an object file
Message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Message.cpp.o
.PHONY : Message.cpp.o

Message.i: Message.cpp.i
.PHONY : Message.i

# target to preprocess a source file
Message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Message.cpp.i
.PHONY : Message.cpp.i

Message.s: Message.cpp.s
.PHONY : Message.s

# target to generate assembly for a file
Message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Message.cpp.s
.PHONY : Message.cpp.s

SQLdataBase.o: SQLdataBase.cpp.o
.PHONY : SQLdataBase.o

# target to build an object file
SQLdataBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/SQLdataBase.cpp.o
.PHONY : SQLdataBase.cpp.o

SQLdataBase.i: SQLdataBase.cpp.i
.PHONY : SQLdataBase.i

# target to preprocess a source file
SQLdataBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/SQLdataBase.cpp.i
.PHONY : SQLdataBase.cpp.i

SQLdataBase.s: SQLdataBase.cpp.s
.PHONY : SQLdataBase.s

# target to generate assembly for a file
SQLdataBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/SQLdataBase.cpp.s
.PHONY : SQLdataBase.cpp.s

Server.o: Server.cpp.o
.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i
.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s
.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/Server.cpp.s
.PHONY : Server.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.out.dir/build.make CMakeFiles/chat.out.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chat.out"
	@echo "... AuthData.o"
	@echo "... AuthData.i"
	@echo "... AuthData.s"
	@echo "... Chat.o"
	@echo "... Chat.i"
	@echo "... Chat.s"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... Connection.o"
	@echo "... Connection.i"
	@echo "... Connection.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... Message.o"
	@echo "... Message.i"
	@echo "... Message.s"
	@echo "... SQLdataBase.o"
	@echo "... SQLdataBase.i"
	@echo "... SQLdataBase.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

